CREATE TABLE EMP AS SELECT  * FPOM EPLOYEE;

DROP TABLE MYTEST;

CREATE TABLE MYTEST(
	MNO NUMBER(10),
	MNAME VARCHAR2(20),
	NICKNAME VARCHAR2(20)
);

ALTER TABLE MYTEST ADD CONSTRAINT UK UNIQUE(MNO);
SELECT * FROM MYTEST;