DROP SEQUENCE MVCBOARDSEQ;
DROP TABLE MVCBOARD;

CREATE SEQUENCE MVCBOARDSEQ;

--번호 , 작성자 , 제목 , 내용 , 작성일자
CREATE TABLE MVCBOARD(
	 SEQ NUMBER PRIMARY KEY,
	 WRITER VARCHAR2(100) NOT NULL,
	 TITLE VARCHAR2(2000) NOT NULL,
	 CONTENT VARCHAR2(2000) NOT NULL,
	 REGDATE DATE NOT NULL
);

INSERT INTO MVCBOARD VALUES
(MVCBOARDSEQ.NEXTVAL , '관리자' , '테스트' , '테스트중입니다...ABCD1234' , SYSDATE);
SELECT * FROM MVCBOARD;